// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HGG1WLtYtS-Tdpf3JiEbiuPG4U5bc_U',
    appId: '1:785507183168:web:8935cfccf22036911e4da5',
    messagingSenderId: '785507183168',
    projectId: 'fir-flutter-codelab-28baa',
    authDomain: 'fir-flutter-codelab-28baa.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-28baa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwOQDeScbuATI9IZXj1bZco1fuWnCYcXY',
    appId: '1:862915485404:android:6803c205a3af31b8e5de19',
    messagingSenderId: '862915485404',
    projectId: 'fir-codelab2-fb257',
    storageBucket: 'fir-codelab2-fb257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1lrWK9KAUPiM8FjHpqb2J7BTlmQyWioM',
    appId: '1:785507183168:ios:e4a4eeb090bcb8981e4da5',
    messagingSenderId: '785507183168',
    projectId: 'fir-flutter-codelab-28baa',
    storageBucket: 'fir-flutter-codelab-28baa.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1lrWK9KAUPiM8FjHpqb2J7BTlmQyWioM',
    appId: '1:785507183168:ios:e4a4eeb090bcb8981e4da5',
    messagingSenderId: '785507183168',
    projectId: 'fir-flutter-codelab-28baa',
    storageBucket: 'fir-flutter-codelab-28baa.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3HGG1WLtYtS-Tdpf3JiEbiuPG4U5bc_U',
    appId: '1:785507183168:web:89adf087c14d01c01e4da5',
    messagingSenderId: '785507183168',
    projectId: 'fir-flutter-codelab-28baa',
    authDomain: 'fir-flutter-codelab-28baa.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-28baa.appspot.com',
  );

}